apiVersion: automation.kubensync.com/v1alpha1
kind: ManagedResource
metadata:
  labels:
    app.kubernetes.io/name: managedresource
    app.kubernetes.io/instance: managedresource-sample
    app.kubernetes.io/part-of: kubensync
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubensync
  name: managedresource-sample
spec:
  namespaceSelector:
    regex: "test"
  template:
    literal: |
      ---
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: managed-resource-sa
        namespace: {{ .Namespace.Name }}

